#!/bin/sh

#docker run -i -t --name mysql_data cannesalair/mysql_datastore
#docker build -t cannesalair/backend .

#docker ps -a -q | xargs docker rm -f

#docker run --name cal_mysql -e MYSQL_ROOT_PASSWORD=gpIDdmdp2014 -d -v /home/cal/cannesalair.fr/cal_mysql/var/lib/mysql:/var/lib/mysql mysql
#docker run --name cal_mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=gpIDdmdp2014 -d -v /home/cal/cannesalair.fr/cal_mysql/var/lib/mysql:/var/lib/mysql mysql
#docker run --name cal_backend -d -v /home/cal/cannesalair.fr/cal/cannesalair:/cannesalair --link=cal_mysql:mysqlcal cannesalair/backend

docker rm -f cal_backend
docker rm -f cal_nginx

docker run --name cal_backend -d -v /home/cal/cannesalair.fr/cal/cannesalair:/cannesalair cannesalair/backend
docker run --name cal_nginx -d --link=cal_backend:backend -v /home/cal/cannesalair.fr/cal_docker/cannesalair-nginx/nginx.cannesalair.config:/etc/nginx/sites-available/default -p 127.0.0.1:9095:9095 --volumes-from=cal_backend dockerfile/nginx

